import type { SceneTemplate } from "@/core/entities";
import { createFrameSpec } from "@/core/value-objects/frame-spec";

/**
 * Courtyard Atrium — two volumes under a strong skylight: north court with
 * garden props, south hang hall linked by a wide opening. Pro tier.
 */
export const courtyardAtriumTemplate: SceneTemplate = {
  id: "courtyard-atrium",
  version: 1,
  name: "Courtyard Atrium",
  tagline: "Twin volumes, strong skylight, garden court",
  category: "atrium",
  tier: "pro",
  status: "active",
  shell: {
    glbPath: "/templates/courtyard-atrium/v1/shell.glb",
    scale: 1,
  },
  environment: {
    exposure: 1.06,
    background: "#c8d0c8",
    toneMapping: "aces",
  },
  lighting: {
    ambient: { color: "#f2f6f2", intensity: 0.28 },
    hemisphere: {
      skyColor: "#eef4f0",
      groundColor: "#a0b0a0",
      intensity: 0.5,
    },
    // Strong overhead skylight key over the court.
    key: {
      color: "#f8fcf8",
      intensity: 1.55,
      position: [0.2, 11.2, -4.5],
    },
    fill: {
      color: "#dce6dc",
      intensity: 0.48,
      position: [6, 3.5, 3],
    },
    rim: {
      color: "#ffffff",
      intensity: 0.16,
      position: [-4, 4.2, 6],
    },
    presets: [
      { id: "sky", label: "Sky", spotIntensity: 0.95, temperatureK: 5400 },
      { id: "court", label: "Court", spotIntensity: 1.05, temperatureK: 5000 },
    ],
  },
  materials: {
    wall: "#f0f2ee",
    wallBand: "#8e9690",
    wallBandBottomM: 0.92,
    wallBandTopM: 2.5,
    floor: "#c4c8bc",
    ceiling: "#f4f6f2",
    trim: "#c8d0c8",
    wallRoughness: 0.94,
    floorRoughness: 0.36,
    floorMetalness: 0.04,
    ceilingRoughness: 0.9,
    floorStyle: "stone",
  },
  architecture: {
    skylight: {
      width: 6.8,
      depth: 7.2,
      gridX: 3,
      gridZ: 4,
      recessM: 0.34,
    },
    window: {
      wallId: "court-west",
      width: 1.4,
      height: 3.6,
      sillM: 0.5,
      offsetM: 0.8,
      arched: true,
    },
    beams: {
      axis: "x",
      count: 6,
      lengthM: 13.5,
      center: [0, 3.5],
      spacingM: 2.2,
      color: "#b8a888",
      widthM: 0.2,
      heightM: 0.26,
    },
    trackLights: {
      axis: "z",
      count: 2,
      spotsPerRail: 6,
      lengthM: 10,
      center: [0, 4.5],
      spacingM: 8.5,
      intensity: 0.36,
      maxLive: 5,
    },
    plinths: [
      { position: [-3.4, 0, -5.2], size: [0.55, 0.95, 0.55] },
      { position: [3.5, 0, -4.8], size: [0.48, 0.78, 0.48] },
      { position: [0, 0, 6.2], size: [0.5, 0.9, 0.5] },
    ],
    benches: [
      {
        position: [0, 0, -2.2],
        size: [2.8, 0.42, 0.5],
        color: "#c4a878",
        glb: true,
      },
      {
        position: [0, 0, 4.0],
        size: [2.4, 0.42, 0.48],
        color: "#c4a878",
        glb: true,
      },
    ],
    glbProps: [
      // Court garden — scaled ~1.1–1.3 m foliage height.
      { model: "plant", position: [-5.6, 0, -8.4], scale: 1.4 },
      { model: "plant", position: [5.6, 0, -8.4], scale: 1.35, yaw: 0.9 },
      { model: "plant", position: [-5.5, 0, -1.6], scale: 1.32, yaw: -0.5 },
      { model: "plant", position: [5.5, 0, -1.6], scale: 1.3, yaw: 1.1 },
      { model: "bust", position: [-3.4, 0.95, -5.2], scale: 1.08 },
      { model: "vase", position: [3.5, 0.78, -4.8], scale: 0.98 },
      { model: "plinth_table", position: [-4.8, 0, 7.4], scale: 1.05 },
      { model: "plant", position: [5.4, 0, 8.2], scale: 1.28, yaw: -0.3 },
      { model: "plant", position: [-5.4, 0, 8.2], scale: 1.25, yaw: 0.6 },
    ],
    signs: [
      {
        text: "COURTYARD ATRIUM",
        subtitle: "North court · South hall",
        position: [0, 4.15, -9.35],
        yaw: 0,
        width: 5.6,
        height: 0.9,
        style: "wall",
      },
      {
        text: "Courtyard Atrium",
        subtitle: "Garden collection",
        position: [0, 0, 8.55],
        yaw: Math.PI,
        width: 1.2,
        height: 0.42,
        style: "plaque",
      },
    ],
  },
  walls: [
    // —— North court (~14 × 10) ——
    {
      id: "court-north",
      label: "Court north",
      origin: [0, 0, -9.5],
      normal: [0, 0, 1],
      width: 14,
      height: 5.6,
      anchors: [
        { position: [-4.0, 1.78, 0.04], maxWidth: 2.2, maxHeight: 2.6 },
        { position: [0, 1.82, 0.04], maxWidth: 2.5, maxHeight: 2.9, preferred: true },
        { position: [4.0, 1.78, 0.04], maxWidth: 2.2, maxHeight: 2.6 },
      ],
    },
    {
      id: "court-east",
      label: "Court east",
      origin: [7, 0, -4.5],
      normal: [-1, 0, 0],
      width: 10,
      height: 5.6,
      anchors: [
        { position: [0.04, 1.75, -2.8], maxWidth: 2.1, maxHeight: 2.4 },
        { position: [0.04, 1.78, 1.5], maxWidth: 2.2, maxHeight: 2.5, preferred: true },
      ],
    },
    {
      id: "court-west",
      label: "Court west",
      origin: [-7, 0, -4.5],
      normal: [1, 0, 0],
      width: 10,
      height: 5.6,
      anchors: [
        // Leave north bay clear for arched window (offset +0.8).
        { position: [-0.04, 1.75, -3.2], maxWidth: 2.0, maxHeight: 2.4 },
        { position: [-0.04, 1.75, 2.4], maxWidth: 2.1, maxHeight: 2.4 },
      ],
    },
    // Partition at z = 0.5 — opening |x| < 3.6
    {
      id: "partition-east",
      label: "Partition east",
      origin: [5.3, 0, 0.5],
      normal: [0, 0, 1],
      width: 3.4,
      height: 5.4,
      anchors: [],
    },
    {
      id: "partition-west",
      label: "Partition west",
      origin: [-5.3, 0, 0.5],
      normal: [0, 0, 1],
      width: 3.4,
      height: 5.4,
      anchors: [],
    },
    {
      id: "partition-east-back",
      label: "Partition east (south face)",
      origin: [5.3, 0, 0.5],
      normal: [0, 0, -1],
      width: 3.4,
      height: 5.4,
      anchors: [
        { position: [0.4, 1.7, -0.04], maxWidth: 1.6, maxHeight: 1.9 },
      ],
    },
    {
      id: "partition-west-back",
      label: "Partition west (south face)",
      origin: [-5.3, 0, 0.5],
      normal: [0, 0, -1],
      width: 3.4,
      height: 5.4,
      anchors: [
        { position: [-0.4, 1.7, -0.04], maxWidth: 1.6, maxHeight: 1.9 },
      ],
    },
    {
      id: "partition-lintel",
      label: "Partition lintel",
      origin: [0, 4.2, 0.5],
      normal: [0, 0, 1],
      width: 7.4,
      height: 1.4,
      anchors: [],
    },
    // —— South hang hall (~14 × 9) ——
    {
      id: "hall-south",
      label: "Hall south",
      origin: [0, 0, 9.5],
      normal: [0, 0, -1],
      width: 14,
      height: 5.2,
      anchors: [
        { position: [-3.8, 1.72, -0.04], maxWidth: 2.2, maxHeight: 2.5 },
        { position: [0, 1.75, -0.04], maxWidth: 2.4, maxHeight: 2.7, preferred: true },
        { position: [3.8, 1.72, -0.04], maxWidth: 2.2, maxHeight: 2.5 },
      ],
    },
    {
      id: "hall-east",
      label: "Hall east",
      origin: [7, 0, 5],
      normal: [-1, 0, 0],
      width: 9,
      height: 5.2,
      anchors: [
        { position: [0.04, 1.7, -2.2], maxWidth: 2.0, maxHeight: 2.3 },
        { position: [0.04, 1.72, 2.0], maxWidth: 2.1, maxHeight: 2.4 },
      ],
    },
    {
      id: "hall-west",
      label: "Hall west",
      origin: [-7, 0, 5],
      normal: [1, 0, 0],
      width: 9,
      height: 5.2,
      anchors: [
        { position: [-0.04, 1.7, -2.2], maxWidth: 2.0, maxHeight: 2.3 },
        { position: [-0.04, 1.72, 2.0], maxWidth: 2.1, maxHeight: 2.4 },
      ],
    },
  ],
  spawn: { position: [0, 1.65, 6.5], yaw: Math.PI },
  // Court + hall with neck through the centred partition opening.
  walkBounds: [
    [-6.2, -8.7],
    [6.2, -8.7],
    [6.2, 0.15],
    [3.45, 0.15],
    [3.45, 0.85],
    [6.2, 0.85],
    [6.2, 8.7],
    [-6.2, 8.7],
    [-6.2, 0.85],
    [-3.45, 0.85],
    [-3.45, 0.15],
    [-6.2, 0.15],
  ],
  capacity: { recommended: 20, max: 26 },
  frameDefaults: createFrameSpec({
    style: "gallery",
    color: "#1e2420",
    widthCm: 2.4,
    matteCm: 5.5,
    matteColor: "#f4f6f2",
  }),
  preview: { imagePath: "/templates/courtyard-atrium/preview.jpg" },
};
