import type { SceneTemplate } from "@/core/entities";
import { createFrameSpec } from "@/core/value-objects/frame-spec";

/**
 * Grand Nave — long high hall with exposed timber beams, track lights, and a
 * deep sightline into a rear gallery volume. Metasteps-scale free showcase.
 */
export const grandNaveTemplate: SceneTemplate = {
  id: "grand-nave",
  version: 1,
  name: "Grand Nave",
  tagline: "Long beamed nave, track lights, deep rear hall",
  category: "museum",
  tier: "free",
  status: "active",
  shell: {
    glbPath: "/templates/grand-nave/v1/shell.glb",
    scale: 1,
  },
  environment: {
    exposure: 1.14,
    background: "#d4d8de",
    toneMapping: "aces",
  },
  lighting: {
    ambient: { color: "#f5f6f8", intensity: 0.36 },
    hemisphere: {
      skyColor: "#eef2f6",
      groundColor: "#b8a888",
      intensity: 0.48,
    },
    key: {
      color: "#f8fafc",
      intensity: 1.28,
      position: [0.6, 10.5, 2],
    },
    fill: {
      color: "#e4eaf2",
      intensity: 0.42,
      position: [-8, 3.8, -4],
    },
    rim: {
      color: "#ffffff",
      intensity: 0.16,
      position: [4, 4.5, -14],
    },
    presets: [
      { id: "daylight", label: "Daylight", spotIntensity: 1.1, temperatureK: 5200 },
      { id: "museum", label: "Museum", spotIntensity: 1.05, temperatureK: 4600 },
    ],
  },
  materials: {
    wall: "#f5f5f4",
    floor: "#d2b896",
    ceiling: "#f0f1f2",
    trim: "#d8d9dc",
    wallRoughness: 0.94,
    floorRoughness: 0.52,
    floorMetalness: 0.03,
    ceilingRoughness: 0.9,
    floorStyle: "plank",
  },
  architecture: {
    beams: {
      axis: "x",
      count: 11,
      lengthM: 13.2,
      center: [0, -1],
      spacingM: 2.35,
      color: "#c4a06a",
      widthM: 0.22,
      heightM: 0.28,
    },
    trackLights: {
      axis: "z",
      count: 2,
      spotsPerRail: 8,
      lengthM: 22,
      center: [0, -1],
      spacingM: 4.2,
      intensity: 0.56,
    },
    benches: [
      { position: [0, 0, 4.5], size: [2.4, 0.42, 0.48], color: "#c9a878", glb: true },
      { position: [0, 0, -1.5], size: [2.6, 0.42, 0.48], color: "#c9a878", glb: true },
      { position: [0, 0, -7.2], size: [2.2, 0.42, 0.48], color: "#c9a878", glb: true },
    ],
    plinths: [{ position: [0, 0, -13.5], size: [0.5, 0.85, 0.5] }],
    glbProps: [
      { model: "bust", position: [0, 0.85, -13.5], scale: 1.1 },
      { model: "plant", position: [5.4, 0, 8.2], scale: 1.35 },
      { model: "plant", position: [-5.4, 0, 8.2], scale: 1.3, yaw: 0.8 },
      { model: "plant", position: [4.8, 0, -16.2], scale: 1.25, yaw: -0.5 },
      { model: "plant", position: [-4.8, 0, -16.2], scale: 1.28, yaw: 1.1 },
      { model: "vase", position: [5.2, 0, -1.5], scale: 1.15 },
      { model: "plinth_table", position: [-5.0, 0, -1.5], scale: 1.05 },
    ],
  },
  walls: [
    // —— Main nave (14 × 20 m, 5.5 m high) ——
    {
      id: "nave-south",
      label: "Nave south",
      origin: [0, 0, 10],
      normal: [0, 0, -1],
      width: 14,
      height: 5.5,
      anchors: [
        { position: [-4.2, 1.7, -0.04], maxWidth: 2.2, maxHeight: 2.6 },
        { position: [0, 1.72, -0.04], maxWidth: 2.4, maxHeight: 2.8 },
        { position: [4.2, 1.7, -0.04], maxWidth: 2.2, maxHeight: 2.6 },
      ],
    },
    {
      id: "nave-east",
      label: "Nave east",
      origin: [7, 0, 0],
      normal: [-1, 0, 0],
      width: 20,
      height: 5.5,
      anchors: [
        { position: [0.04, 1.7, -7.2], maxWidth: 2.1, maxHeight: 2.5 },
        { position: [0.04, 1.72, -3.6], maxWidth: 2.2, maxHeight: 2.6 },
        { position: [0.04, 1.72, 0], maxWidth: 2.3, maxHeight: 2.7, preferred: true },
        { position: [0.04, 1.72, 3.6], maxWidth: 2.2, maxHeight: 2.6 },
        { position: [0.04, 1.7, 7.2], maxWidth: 2.1, maxHeight: 2.5 },
      ],
    },
    {
      id: "nave-west",
      label: "Nave west",
      origin: [-7, 0, 0],
      normal: [1, 0, 0],
      width: 20,
      height: 5.5,
      anchors: [
        { position: [-0.04, 1.7, -7.2], maxWidth: 2.1, maxHeight: 2.5 },
        { position: [-0.04, 1.72, -3.6], maxWidth: 2.2, maxHeight: 2.6 },
        { position: [-0.04, 1.72, 0], maxWidth: 2.3, maxHeight: 2.7, preferred: true },
        { position: [-0.04, 1.72, 3.6], maxWidth: 2.2, maxHeight: 2.6 },
        { position: [-0.04, 1.7, 7.2], maxWidth: 2.1, maxHeight: 2.5 },
      ],
    },
    // Partition at z = -10 — wide opening |x| < 4.2
    {
      id: "partition-east",
      label: "Partition east",
      origin: [5.6, 0, -10],
      normal: [0, 0, 1],
      width: 2.8,
      height: 5.5,
      anchors: [],
    },
    {
      id: "partition-west",
      label: "Partition west",
      origin: [-5.6, 0, -10],
      normal: [0, 0, 1],
      width: 2.8,
      height: 5.5,
      anchors: [],
    },
    {
      id: "partition-east-back",
      label: "Partition east (rear)",
      origin: [5.6, 0, -10],
      normal: [0, 0, -1],
      width: 2.8,
      height: 5.5,
      anchors: [
        { position: [0.4, 1.65, -0.04], maxWidth: 1.6, maxHeight: 1.9 },
      ],
    },
    {
      id: "partition-west-back",
      label: "Partition west (rear)",
      origin: [-5.6, 0, -10],
      normal: [0, 0, -1],
      width: 2.8,
      height: 5.5,
      anchors: [
        { position: [-0.4, 1.65, -0.04], maxWidth: 1.6, maxHeight: 1.9 },
      ],
    },
    {
      id: "partition-lintel",
      label: "Partition lintel",
      origin: [0, 4.15, -10],
      normal: [0, 0, 1],
      width: 8.6,
      height: 1.35,
      anchors: [],
    },
    // —— Rear gallery ——
    {
      id: "rear-north",
      label: "Rear north",
      origin: [0, 0, -18],
      normal: [0, 0, 1],
      width: 12,
      height: 5.2,
      anchors: [
        { position: [-3.2, 1.68, 0.04], maxWidth: 2.2, maxHeight: 2.5 },
        { position: [0, 1.7, 0.04], maxWidth: 2.5, maxHeight: 2.8, preferred: true },
        { position: [3.2, 1.68, 0.04], maxWidth: 2.2, maxHeight: 2.5 },
      ],
    },
    {
      id: "rear-east",
      label: "Rear east",
      origin: [6, 0, -14],
      normal: [-1, 0, 0],
      width: 8,
      height: 5.2,
      anchors: [
        { position: [0.04, 1.65, -1.8], maxWidth: 2.0, maxHeight: 2.3 },
        { position: [0.04, 1.65, 1.8], maxWidth: 2.0, maxHeight: 2.3 },
      ],
    },
    {
      id: "rear-west",
      label: "Rear west",
      origin: [-6, 0, -14],
      normal: [1, 0, 0],
      width: 8,
      height: 5.2,
      anchors: [
        { position: [-0.04, 1.65, -1.8], maxWidth: 2.0, maxHeight: 2.3 },
        { position: [-0.04, 1.65, 1.8], maxWidth: 2.0, maxHeight: 2.3 },
      ],
    },
  ],
  spawn: { position: [0, 1.65, 7.5], yaw: Math.PI },
  walkBounds: [
    [-5.5, -17.5],
    [5.5, -17.5],
    [5.5, -10.25],
    [4.05, -10.25],
    [4.05, -9.75],
    [6.4, -9.75],
    [6.4, 9.5],
    [-6.4, 9.5],
    [-6.4, -9.75],
    [-4.05, -9.75],
    [-4.05, -10.25],
    [-5.5, -10.25],
  ],
  capacity: { recommended: 22, max: 30 },
  frameDefaults: createFrameSpec({
    style: "gallery",
    color: "#1a1c1e",
    widthCm: 2.4,
    matteCm: 5,
    matteColor: "#f6f6f5",
  }),
  preview: { imagePath: "/templates/grand-nave/preview.jpg" },
};
