import type { SceneTemplate } from "@/core/entities";
import { createFrameSpec } from "@/core/value-objects/frame-spec";

/**
 * Plaza Hall — very large footprint (~20 × 16 m) with a side wing opening so
 * Walk feels expansive rather than a single box. Free tier.
 */
export const plazaHallTemplate: SceneTemplate = {
  id: "plaza-hall",
  version: 1,
  name: "Plaza Hall",
  tagline: "Wide plaza, beamed ceiling, side wing opening",
  category: "museum",
  tier: "free",
  status: "active",
  shell: {
    glbPath: "/templates/plaza-hall/v1/shell.glb",
    scale: 1,
  },
  environment: {
    exposure: 1.12,
    background: "#d6d9de",
    toneMapping: "aces",
  },
  lighting: {
    ambient: { color: "#f4f5f7", intensity: 0.35 },
    hemisphere: {
      skyColor: "#eef2f6",
      groundColor: "#b5a584",
      intensity: 0.46,
    },
    key: {
      color: "#f7f9fc",
      intensity: 1.22,
      position: [-1, 9.8, 1.5],
    },
    fill: {
      color: "#e2e8f0",
      intensity: 0.4,
      position: [12, 3.5, -2],
    },
    rim: {
      color: "#ffffff",
      intensity: 0.15,
      position: [8, 4, -6],
    },
    presets: [
      { id: "daylight", label: "Daylight", spotIntensity: 1.08, temperatureK: 5100 },
    ],
  },
  materials: {
    wall: "#f4f4f3",
    floor: "#d0b690",
    ceiling: "#eef0f2",
    trim: "#d6d8dc",
    wallRoughness: 0.94,
    floorRoughness: 0.38,
    floorMetalness: 0.05,
    ceilingRoughness: 0.9,
    floorStyle: "plank",
    floorTextureId: "wood_plank",
    wallTextureId: "plaster_smooth",
  },
  architecture: {
    beams: {
      axis: "x",
      count: 9,
      lengthM: 18.5,
      center: [0, 0],
      spacingM: 2.1,
      color: "#c2a068",
      widthM: 0.2,
      heightM: 0.26,
    },
    trackLights: {
      axis: "z",
      count: 3,
      spotsPerRail: 6,
      lengthM: 14,
      center: [0, 0],
      spacingM: 5.5,
      intensity: 0.45,
    },
    benches: [
      { position: [-3.5, 0, 2], size: [2.8, 0.42, 0.5], color: "#c8a674", glb: true },
      { position: [3.5, 0, 2], size: [2.8, 0.42, 0.5], color: "#c8a674", glb: true },
      { position: [0, 0, -3.5], size: [3.2, 0.42, 0.5], color: "#c8a674", glb: true },
    ],
    glbProps: [
      { model: "plant", position: [8.6, 0, 6.4], scale: 1.35 },
      { model: "plant", position: [-8.6, 0, 6.4], scale: 1.3, yaw: 0.7 },
      { model: "plant", position: [8.4, 0, -6.2], scale: 1.25, yaw: -0.3 },
      { model: "plant", position: [-8.4, 0, -6.2], scale: 1.28, yaw: 1.2 },
      { model: "vase", position: [0, 0, 5.5], scale: 1.2 },
      { model: "plinth_table", position: [0, 0, 6.4], scale: 1.1 },
      { model: "bust", position: [0, 0.55, 6.4], scale: 1.0 },
    ],
  },
  walls: [
    // —— Main plaza 20 × 16 ——
    {
      id: "plaza-north",
      label: "Plaza north",
      origin: [0, 0, -8],
      normal: [0, 0, 1],
      width: 20,
      height: 5.2,
      anchors: [
        { position: [-6.5, 1.68, 0.04], maxWidth: 2.2, maxHeight: 2.5 },
        { position: [-3.2, 1.7, 0.04], maxWidth: 2.3, maxHeight: 2.6 },
        { position: [0, 1.72, 0.04], maxWidth: 2.5, maxHeight: 2.8, preferred: true },
        { position: [3.2, 1.7, 0.04], maxWidth: 2.3, maxHeight: 2.6 },
        { position: [6.5, 1.68, 0.04], maxWidth: 2.2, maxHeight: 2.5 },
      ],
    },
    {
      id: "plaza-south",
      label: "Plaza south",
      origin: [0, 0, 8],
      normal: [0, 0, -1],
      width: 20,
      height: 5.2,
      anchors: [
        { position: [-5.5, 1.68, -0.04], maxWidth: 2.2, maxHeight: 2.5 },
        { position: [-2, 1.7, -0.04], maxWidth: 2.2, maxHeight: 2.5 },
        { position: [2, 1.7, -0.04], maxWidth: 2.2, maxHeight: 2.5 },
        { position: [5.5, 1.68, -0.04], maxWidth: 2.2, maxHeight: 2.5 },
      ],
    },
    {
      id: "plaza-west",
      label: "Plaza west",
      origin: [-10, 0, 0],
      normal: [1, 0, 0],
      width: 16,
      height: 5.2,
      anchors: [
        { position: [-0.04, 1.68, -5], maxWidth: 2.1, maxHeight: 2.4 },
        { position: [-0.04, 1.7, -1.8], maxWidth: 2.2, maxHeight: 2.5 },
        { position: [-0.04, 1.7, 1.8], maxWidth: 2.2, maxHeight: 2.5, preferred: true },
        { position: [-0.04, 1.68, 5], maxWidth: 2.1, maxHeight: 2.4 },
      ],
    },
    // East wall — gap for wing at z ∈ [-2.4, 2.4]
    {
      id: "plaza-east-north",
      label: "Plaza east north",
      origin: [10, 0, -5.2],
      normal: [-1, 0, 0],
      width: 5.6,
      height: 5.2,
      anchors: [
        { position: [0.04, 1.68, 0], maxWidth: 2.1, maxHeight: 2.4 },
      ],
    },
    {
      id: "plaza-east-south",
      label: "Plaza east south",
      origin: [10, 0, 5.2],
      normal: [-1, 0, 0],
      width: 5.6,
      height: 5.2,
      anchors: [
        { position: [0.04, 1.68, 0], maxWidth: 2.1, maxHeight: 2.4 },
      ],
    },
    {
      id: "wing-opening-lintel",
      label: "Wing opening lintel",
      origin: [10, 3.95, 0],
      normal: [-1, 0, 0],
      width: 5,
      height: 1.25,
      anchors: [],
    },
    // —— East wing ——
    {
      id: "wing-east",
      label: "Wing east",
      origin: [18, 0, 0],
      normal: [-1, 0, 0],
      width: 10,
      height: 4.8,
      anchors: [
        { position: [0.04, 1.65, -2.8], maxWidth: 2.1, maxHeight: 2.4 },
        { position: [0.04, 1.68, 0], maxWidth: 2.3, maxHeight: 2.6, preferred: true },
        { position: [0.04, 1.65, 2.8], maxWidth: 2.1, maxHeight: 2.4 },
      ],
    },
    {
      id: "wing-north",
      label: "Wing north",
      origin: [14, 0, -5],
      normal: [0, 0, 1],
      width: 8,
      height: 4.8,
      anchors: [
        { position: [-1.8, 1.62, 0.04], maxWidth: 2.0, maxHeight: 2.3 },
        { position: [1.8, 1.62, 0.04], maxWidth: 2.0, maxHeight: 2.3 },
      ],
    },
    {
      id: "wing-south",
      label: "Wing south",
      origin: [14, 0, 5],
      normal: [0, 0, -1],
      width: 8,
      height: 4.8,
      anchors: [
        { position: [-1.8, 1.62, -0.04], maxWidth: 2.0, maxHeight: 2.3 },
        { position: [1.8, 1.62, -0.04], maxWidth: 2.0, maxHeight: 2.3 },
      ],
    },
    {
      id: "wing-west-north",
      label: "Wing west north",
      origin: [10, 0, -3.7],
      normal: [1, 0, 0],
      width: 2.6,
      height: 4.8,
      anchors: [],
    },
    {
      id: "wing-west-south",
      label: "Wing west south",
      origin: [10, 0, 3.7],
      normal: [1, 0, 0],
      width: 2.6,
      height: 4.8,
      anchors: [],
    },
  ],
  spawn: { position: [0, 1.65, 5.5], yaw: Math.PI },
  walkBounds: [
    [-9.3, -7.3],
    [9.5, -7.3],
    [9.5, -2.25],
    [17.5, -2.25],
    [17.5, 2.25],
    [9.5, 2.25],
    [9.5, 7.3],
    [-9.3, 7.3],
  ],
  capacity: { recommended: 24, max: 32 },
  frameDefaults: createFrameSpec({
    style: "gallery",
    color: "#1c1e20",
    widthCm: 2.4,
    matteCm: 5,
    matteColor: "#f5f5f4",
  }),
  preview: { imagePath: "/templates/plaza-hall/preview.jpg" },
};
